function AllCases = build_sia_cases(R_total, r_core, ...
                                     r_source_nonoverlap, r_detector_nonoverlap, sep_nonoverlap, ...
                                     side_source_square, side_detector_square, detector_offset_square_mm, ...
                                     gaussian_w_mm, R_detector_gauss, Nw_cap)
% BUILD_SIA_CASES  Construct the cell array of source-detector geometry structs.
%
%  AllCases = build_sia_cases(R_total, r_core, ...)
%
%  This function centralises all source-detector geometry definitions for
%  the SIA demonstration script. Each entry of AllCases is a struct that
%  fully describes one scenario, including shape parameters, offsets, and
%  metadata linking it back to the Letter.
%
%  Extracting the definitions here keeps the main demo script concise and
%  makes it easy to add new geometries without touching the main loop.
%
%  INPUTS (all in mm or dimensionless where noted)
%  ------------------------------------------------
%  R_total                  - outer radius of full disk / annulus [mm]
%  r_core                   - inner (core) radius [mm]
%  r_source_nonoverlap      - source disk radius for Case IV [mm]
%  r_detector_nonoverlap    - detector disk radius for Case IV [mm]
%  sep_nonoverlap           - centre-to-centre separation for Case IV [mm]
%  side_source_square       - source square side length for Case V [mm]
%  side_detector_square     - detector square side length for Case V [mm]
%  detector_offset_square_mm- [dx, dy] offset of square detector centre [mm]
%  gaussian_w_mm            - Gaussian beam waist (1/e^2 radius) for Case VI [mm]
%  R_detector_gauss         - hard aperture radius of Gaussian detector [mm]
%  Nw_cap                   - truncation cap factor: R_src = R_det + Nw_cap*w
%                             (dimensionless)
%
%  OUTPUT
%  ------
%  AllCases  - (1 x 7) cell array of geometry structs with fields:
%
%    display_name       - human-readable label shown in figures and console
%    letter_group       - letter identifier ('I'..'VI' or 'extra')
%    appears_in_letter  - true if this scenario is in the published Letter
%    type               - geometry class:
%                           'uniform_shapes'   disk/annulus with uniform weighting
%                           'square_square'    square source and detector
%                           'gaussian_overlap' Gaussian-weighted source+detector
%
%    For 'uniform_shapes' cases:
%      source_shape      - 'disk' or 'annulus'
%      source_rin        - source inner radius [mm] (0 for disk)
%      source_rout       - source outer radius [mm]
%      source_side       - [] (not used)
%      detector_shape    - 'disk' or 'annulus'
%      detector_rin      - detector inner radius [mm]
%      detector_rout     - detector outer radius [mm]
%      detector_side     - [] (not used)
%      detector_offset_mm- [dx, dy] lateral displacement of detector centre [mm]
%
%    For 'square_square' cases:
%      source_shape, detector_shape  - 'square'
%      source_side, detector_side    - side lengths [mm]
%      source_rin, source_rout       - [] (not used)
%      detector_rin, detector_rout   - [] (not used)
%      detector_offset_mm            - [dx, dy] offset [mm]
%
%    For 'gaussian_overlap' cases:
%      w_mm              - Gaussian waist radius [mm]
%      R_det_mm          - detector hard aperture radius [mm]
%      Nw_cap            - source truncation factor (dimensionless)
%      detector_offset_mm- [0, 0] (always concentric for this case)
%
%  MANUSCRIPT MAPPING
%  ------------------
%  Scenario I   : Case 1 (uniform overlapping disk -> disk)
%  Scenario II  : Case 3 (annulus -> annulus, concentric)
%  Scenario III : Case 4 (core disk -> cladding annulus, concentric)
%  Scenario IV  : Case 5 (non-overlapping disks)
%  Scenario V   : Case 6 (square -> square, touching corners)
%  Scenario VI  : Case 7 (Gaussian source + Gaussian-weighted detector)
%  Extra        : Case 2 (core -> total, demo only, not in Letter)

AllCases = { ...

    % ------------------------------------------------------------------
    % Case I  (Letter scenario I)
    % Uniformly illuminated disk source and disk detector of equal radius,
    % fully overlapping and concentric. This corresponds to a single-fiber
    % configuration where source and detector share the same aperture.
    % ------------------------------------------------------------------
    struct('display_name',      'I) Disk -> disk (uniform overlap)', ...
           'letter_group',       'I', ...
           'appears_in_letter',  true, ...
           'type',               'uniform_shapes', ...
           'source_shape',       'disk', ...
           'source_rin',         0, ...
           'source_rout',        R_total, ...
           'source_side',        [], ...
           'detector_shape',     'disk', ...
           'detector_rin',       0, ...
           'detector_rout',      R_total, ...
           'detector_side',      [], ...
           'detector_offset_mm', [0 0]), ...

    % ------------------------------------------------------------------
    % Extra case  (demo only, not in the Letter)
    % Concentric disk source (core) and larger disk detector (total).
    % Included as an additional sanity check; omitted from the Letter
    % because it does not add validation beyond the other concentric cases.
    % ------------------------------------------------------------------
    struct('display_name',      'Extra) Core -> total (concentric disk -> disk)', ...
           'letter_group',       'extra', ...
           'appears_in_letter',  false, ...
           'type',               'uniform_shapes', ...
           'source_shape',       'disk', ...
           'source_rin',         0, ...
           'source_rout',        r_core, ...
           'source_side',        [], ...
           'detector_shape',     'disk', ...
           'detector_rin',       0, ...
           'detector_rout',      R_total, ...
           'detector_side',      [], ...
           'detector_offset_mm', [0 0]), ...

    % ------------------------------------------------------------------
    % Case II  (Letter scenario II)
    % Concentric annular source and annular detector with identical inner
    % and outer radii. Representative of the cladding of a double-clad fiber.
    % ------------------------------------------------------------------
    struct('display_name',      'II) Annulus -> annulus (concentric)', ...
           'letter_group',       'II', ...
           'appears_in_letter',  true, ...
           'type',               'uniform_shapes', ...
           'source_shape',       'annulus', ...
           'source_rin',         r_core, ...
           'source_rout',        R_total, ...
           'source_side',        [], ...
           'detector_shape',     'annulus', ...
           'detector_rin',       r_core, ...
           'detector_rout',      R_total, ...
           'detector_side',      [], ...
           'detector_offset_mm', [0 0]), ...

    % ------------------------------------------------------------------
    % Case III  (Letter scenario III)
    % Central disk source (core) and concentric annular detector (cladding).
    % Represents the launch-through-core / detect-via-cladding configuration
    % of a double-clad fiber.
    % ------------------------------------------------------------------
    struct('display_name',      'III) Core -> cladding (concentric disk -> annulus)', ...
           'letter_group',       'III', ...
           'appears_in_letter',  true, ...
           'type',               'uniform_shapes', ...
           'source_shape',       'disk', ...
           'source_rin',         0, ...
           'source_rout',        r_core, ...
           'source_side',        [], ...
           'detector_shape',     'annulus', ...
           'detector_rin',       r_core, ...
           'detector_rout',      R_total, ...
           'detector_side',      [], ...
           'detector_offset_mm', [0 0]), ...

    % ------------------------------------------------------------------
    % Case IV  (Letter scenario IV)
    % Two laterally separated (non-overlapping) disks. Relevant to diffuse
    % reflectance spectroscopy where source and detector fibers are separate.
    % The centre-to-centre separation sep_nonoverlap is defined in the
    % calling script as r_source + r_detector + 0.25*R_total (a small gap).
    % ------------------------------------------------------------------
    struct('display_name',      'IV) Non-overlapping disks', ...
           'letter_group',       'IV', ...
           'appears_in_letter',  true, ...
           'type',               'uniform_shapes', ...
           'source_shape',       'disk', ...
           'source_rin',         0, ...
           'source_rout',        r_source_nonoverlap, ...
           'source_side',        [], ...
           'detector_shape',     'disk', ...
           'detector_rin',       0, ...
           'detector_rout',      r_detector_nonoverlap, ...
           'detector_side',      [], ...
           'detector_offset_mm', [sep_nonoverlap 0]), ...

    % ------------------------------------------------------------------
    % Case V  (Letter scenario V)
    % Square source and square detector of equal side length, offset so
    % that their corners touch diagonally. Relevant to structured
    % illumination and detection with rectangular apertures.
    % ------------------------------------------------------------------
    struct('display_name',      'V) Square -> square (touching corners)', ...
           'letter_group',       'V', ...
           'appears_in_letter',  true, ...
           'type',               'square_square', ...
           'source_shape',       'square', ...
           'source_rin',         [], ...
           'source_rout',        [], ...
           'source_side',        side_source_square, ...
           'detector_shape',     'square', ...
           'detector_rin',       [], ...
           'detector_rout',      [], ...
           'detector_side',      side_detector_square, ...
           'detector_offset_mm', detector_offset_square_mm), ...

    % ------------------------------------------------------------------
    % Case VI  (Letter scenario VI)
    % Gaussian-weighted source and Gaussian-weighted detector clipped to a
    % finite circular aperture. The effective distance distribution p_eff(rho)
    % is obtained from the weighted cross-covariogram (Letter Eq. 4 and
    % Supplemental). This tests the non-uniform illumination/detection
    % extension of the SIA framework.
    % ------------------------------------------------------------------
    struct('display_name',      'VI) Gaussian source + Gaussian-weighted detector', ...
           'letter_group',       'VI', ...
           'appears_in_letter',  true, ...
           'type',               'gaussian_overlap', ...
           'w_mm',               gaussian_w_mm, ...
           'R_det_mm',           R_detector_gauss, ...
           'Nw_cap',             Nw_cap, ...
           'detector_offset_mm', [0 0]) ...
    };

end
